import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Sidebar from "@/Components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; 
}) {
  return (
   <html lang="en">
    <body className={'${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white'}>
      <div className="flex h-screen overflow-hidden">
        <Sidebar/>
        <div className="flex flex-col flex-1 overflow-auto">
          <div className="max-w-7xl mx-auto w-full">
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </div>
    </body>
   </html>
  );
}
